//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\zhaoshen\Desktop\创建长方体\create_block.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: zhaoshen
//              Version: NX 1847
//              Date: 06-20-2025  (Format: mm-dd-yyyy)
//              Time: 16:07
//
//==============================================================================

#ifndef CREATE_BLOCK_H_INCLUDED
#define CREATE_BLOCK_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Group.hxx>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport create_block
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    create_block();
    ~create_block();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the create_block.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::DoubleBlock* L1;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* L2;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* L3;// Block type: Double
    NXOpen::BlockStyler::SpecifyPoint* P0;// Block type: Specify Point
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    
};
#endif //CREATE_BLOCK_H_INCLUDED
